### ISSUE TITLE
Edit menu link leads to exception

### ISSUE THREAD

**Issue by lionelhorn** [medusajs/medusa-eats#24]
Hello ! 

Followed the instructions. 

Created restaurant account and logged in. 

Clicking on `Edit link` results in the following error.

<img width="623" alt="image" src="https://github.com/user-attachments/assets/1b1ddab1-8a18-4a22-8589-e39a0d9fc28a">

<img width="696" alt="image" src="https://github.com/user-attachments/assets/dde167af-9b11-4660-bd3a-85ca255371f0">

**Comment by VariableVic** [comment]
Hey @lionelhorn, thanks for the report. #26 should fix the issue. Can I get you to give it a spin locally and let me know if it solves the issue for you? Thanks!
